#!/usr/bin/env python3
"""Bakes two monospace bitmap fonts into src/core/font_data.h.

Each glyph is stored as one byte per pixel row, MSB = leftmost pixel. Glyph
codes 32..127 are covered (96 glyphs); anything outside renders as a space.

Regenerating is only necessary if the cell metrics change - the produced header
is checked in so the build has no Python or font dependency.
"""
import os
from PIL import Image, ImageDraw, ImageFont

FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
FIRST, LAST = 32, 127

# (name, cell width, cell height, point size, baseline row)
VARIANTS = [
    ("kFont8x16", 8, 16, 14, 12),
    ("kFont6x12", 6, 12, 11, 9),
    ("kFont4x8", 4, 8, 8, 6),
]


def bake(cell_w, cell_h, size, baseline):
    font = ImageFont.truetype(FONT_PATH, size)
    rows = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (cell_w, cell_h), 0)
        draw = ImageDraw.Draw(img)
        ch = chr(code)
        # Centre horizontally using the glyph's own advance width.
        try:
            adv = font.getlength(ch)
        except AttributeError:
            adv = font.getsize(ch)[0]
        x = (cell_w - adv) / 2.0
        draw.text((x, baseline), ch, font=font, fill=255, anchor="ls")
        px = img.load()
        for y in range(cell_h):
            bits = 0
            for x in range(cell_w):
                if px[x, y] >= 110:
                    bits |= 1 << (7 - x)
            rows.append(bits)
    return rows


def main():
    out = []
    out.append("// font_data.h - generated by tools/genfont.py. Do not edit by hand.")
    out.append("// 96 glyphs (ASCII 32..127), one byte per pixel row, MSB = leftmost pixel.")
    out.append("#pragma once")
    out.append("")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace sb {")
    out.append("")
    out.append("constexpr int kFontFirstGlyph = 32;")
    out.append("constexpr int kFontGlyphCount = 96;")
    out.append("")
    for name, cw, ch, size, baseline in VARIANTS:
        data = bake(cw, ch, size, baseline)
        out.append("constexpr int %sWidth = %d;" % (name, cw))
        out.append("constexpr int %sHeight = %d;" % (name, ch))
        out.append("constexpr uint8_t %sBits[%d] = {" % (name, len(data)))
        for i in range(0, len(data), ch):
            glyph = data[i:i + ch]
            code = FIRST + i // ch
            label = chr(code) if 33 <= code <= 126 else "sp"
            if label in ("\\", "*", "/"):
                label = "ch%d" % code
            out.append("    " + " ".join("0x%02X," % b for b in glyph) + "  // '%s'" % label)
        out.append("};")
        out.append("")
    out.append("} // namespace sb")

    dest = os.path.join(os.path.dirname(__file__), "..", "src", "core", "font_data.h")
    with open(os.path.normpath(dest), "w") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote", os.path.normpath(dest))


if __name__ == "__main__":
    main()
